language: go
sudo: false

go:
    - 1.11.x
    - 1.10.x

go_import_path: gopkg.in/src-d/go-billy-siva.v4

matrix:
    fast_finish: true
    allow_failures:
        - go: tip

script:
  - make dependencies
  - make test-coverage
  - make codecov

